### ISSUE TITLE
Remove unused frontend packages

### ISSUE THREAD

**Issue by anna-kartynnik** [codeforsanjose/gov-agenda-notifier#108]
I've just looked at [frontend/package.json](https://github.com/codeforsanjose/gov-agenda-notifier/blob/master/frontend/package.json) and I'm confused by some dependencies I can see there. For example, `apollo-server-express`, `express`, `pg` (PostgreSQL dependency for the frontend???), `twilio`, `winston`. I don't think they are used by the frontend but maybe I'm missing anything 🤔 ...

**Comment by terchiem** [comment]
I think they were left over from when the project first started. @teohrt might know more about this but it would be good to go through the packages and trim out any unused ones.

**Comment by cfsjsharedadmin** [comment]
Anna ran into some issues with queries to database after some recent changes.
Roles in backend was named with capital R in one place and wasn't in another place.
