### ISSUE TITLE
Meeting: Admin should be able to create a Meeting

### ISSUE THREAD

**Issue by jeffersonken19** [codeforsanjose/gov-agenda-notifier#113]
As an admin, I should be able to create a Meeting

**Comment by jerrycyip** [comment]
Just wanted to outline initial approach that I'm planning.  Welcome other developers feedback/insights/suggestions especially if I may be missing/overlooking something (such as my initial approach to call the new CreateMeeting functionality from MeetingListView.jsx).  

**Approach:**
Implementation will follow similar pattern to existing functionality for uploading a new meeting agenda and deleting an existing meeting as follows:
- Create custom hook for creating a meeting (e.g. "useCreateMeeting.jsx "similar to useCSVUpload.jsx and useDeleteMeeting.jsx)
- Create corresponding new mutation gql template string for creating a meeting (in frontend/src/graphql/graphql.js).  
- - The new front end mutation gql template string will correspond to existing backend “createMeeting” mutation (in 
backend/graphql_api/graphql/apolloServer.js) and related resolver (in .../resolvers/mutation.js)
- Create new ‘CreateMeeting’ modal component (jsx files similar to DeleteMeetingModal.jsx and CSVUploadModal.jsx) along w/ styling (scss file)
- - The new modal component will employ the aforementioned new custom hook and graphql mutation above.
- - The new CreateMeeting Modal component will be called by “MeetingListView”.  Hence, believe I will also need to update “MeetingListView.jsx” component file and scss styling files to include a new button with react-router-dom ‘Link’ to the CreateMeeting modal.
- - The MeetingListView component will need logic to differentiate between admin and community user roles - similar to current missing logic in “MeetingListItem.jsx” for admin abilities to upload meeting agendas/delete meetings
