### ISSUE TITLE
Deprecate createSubscription once frontend stops using it

### ISSUE THREAD

**Issue by sent-hil** [codeforsanjose/gov-agenda-notifier#132]
https://github.com/codeforsanjose/gov-agenda-notifier/pull/131/files#diff-de54ad10dfd26d4102285b3444ff914619e7712712abe1692d9bcca1a8075496R202

https://github.com/codeforsanjose/gov-agenda-notifier/pull/131/files#diff-c7abd69c68520f406bf4bc35bd6626dcaf6f0943fa6095cd534d2490122c89fdR70

**Comment by anna-kartynnik** [comment]
@sent-hil the client doesn't use `createSubscription` any more

**Comment by sent-hil** [comment]
https://github.com/codeforsanjose/gov-agenda-notifier/pull/141
