### ISSUE TITLE
Look into possible SQL injection due to string interpolation

### ISSUE THREAD

**Issue by sent-hil** [codeforsanjose/gov-agenda-notifier#142]
A whole lot of queries in backend inject into query string like: https://github.com/codeforsanjose/gov-agenda-notifier/blob/master/backend/graphql_api/lambda/db/dbClient.js#L67

```
 query(`SELECT * FROM meeting WHERE id = ${id}`);
```
 
It's possible the SQL library prevents injection under the hood. This story is to check if it.

**Comment by forkitupforkitup** [comment]
Apparently, the library still recommends parameterizing your queries: https://node-postgres.com/features/queries#Parameterized%20query
