### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by abhieshekumar** [codeforsanjose/gov-agenda-notifier#181]
The application has horizontal scroll when viewed.

**Comment by anna-kartynnik** [comment]
Might be fixable by adding `box-sizing: border-box;` CSS style to the Footer component.

**Comment by jerrycyip** [comment]
Anna's suggestion seems to work - I can submit the change as it's small.

**Comment by anna-kartynnik** [comment]
@jerrycyip feel free to create a PR.

**Comment by jerrycyip** [comment]
@anna-kartynnik just submitted the PR = ) Thanks Anna!
