### ISSUE TITLE
Remove the requirement of submitting a meeting_id when subscribing

### ISSUE THREAD

**Issue by jeffersonken19** [codeforsanjose/gov-agenda-notifier#193]
Remove the requirement of submitting a meeting_id when subscribing
They should only have to submit a meeting_item_id when subscribing

**Comment by jerrycyip** [comment]
Looks like this might comprise removing the following from convertQueryStringToServerFormat function?
"        meeting_id: parseInt(meetingParams[0], 10), "

**Comment by anna-kartynnik** [comment]
@jerrycyip your changes would make sense for the frontend but this issue is actually for the backend. We need to remove `meeting_id` from the corresponding endpoint on the server.
