### ISSUE TITLE
Build Admin meeting details form

### ISSUE THREAD

**Issue by aaa12345678910** [codeforsanjose/gov-agenda-notifier#28]
Link to the full mocks:
https://xd.adobe.com/view/093f0ddd-4f69-442b-a46e-48614636913f-5c6c/screen/3c9b6abf-c20b-4e32-b88f-7c85fdb1403f

The section this task focuses on:
<img width="1145" alt="Screen Shot 2020-10-14 at 4 40 13 PM" src="https://user-images.githubusercontent.com/64624067/96057108-0a16ea80-0e3d-11eb-80d6-04b9807b22a0.png">
<img width="1162" alt="Screen Shot 2020-10-14 at 4 48 11 PM" src="https://user-images.githubusercontent.com/64624067/96057116-100ccb80-0e3d-11eb-9381-132f1596ddc1.png">

**Comment by jeffersonken19** [comment]
Sepehr just found a React Form library. Need to do some styling and then hook up with GraphQL.

**Comment by jeffersonken19** [comment]
No PR yet. Sepehr started working on it yesterday.
