### ISSUE TITLE
Figure out how to work on a mongo db instance with multiple people

### ISSUE THREAD

**Issue by aaa12345678910** [codeforsanjose/gov-agenda-notifier#3]
Figure out how to work on a mongo db instance with multiple people

**Comment by teohrt** [comment]
Considering the data we're working with is structured and well defined, I went with a relational database implementation using PostgreSQL.

I'm using a Docker container for our local development purposes:
https://github.com/codeforsanjose/gov-agenda-notifier/tree/master/server/docker/dev

Digital ocean has a reasonable pricing model for DB hosting:
https://www.digitalocean.com/pricing/#managed-databases
