### ISSUE TITLE
Pull Meeting Agenda from GraphQL API

### ISSUE THREAD

**Issue by aaa12345678910** [codeforsanjose/gov-agenda-notifier#31]

**Comment by teohrt** [comment]
I've merged changes disabling the auth requirements for GraphQL while in DEV. This will make this issue easier to start now.

**Comment by sepsol** [comment]
DONE! 
[commit 6c8d68d](https://github.com/codeforsanjose/gov-agenda-notifier/commit/6c8d68d81fc49b3467cb7aee1cb8569a9879b847)
