### ISSUE TITLE
Refactor upload via CSV to match new designs & connect to backend API

### ISSUE THREAD

**Issue by aaa12345678910** [codeforsanjose/gov-agenda-notifier#32]

**Comment by teohrt** [comment]
This functionality will be its own lambda function.

**Comment by teohrt** [comment]
I've submitted a PR addressing the backend portion of this issue. Let me know if you have any thoughts or questions!

**Comment by cfsjsharedadmin** [comment]
@terchiem is running into a CORS error

**Comment by cfsjsharedadmin** [comment]
@terchiem please add a very large header in our README that points to a github issue around removing the CORS allow * policy
