### ISSUE TITLE
Estimate AWS costs: Create a spreadsheet

### ISSUE THREAD

**Issue by aaa12345678910** [codeforsanjose/gov-agenda-notifier#55]
https://docs.google.com/spreadsheets/d/1kUfOFZ1A00ebKPPqnFOiz5ci6U3b082xKb6xY_dXo8Y/edit#gid=1891843870

**Comment by sent-hil** [comment]
https://docs.google.com/spreadsheets/d/1kUfOFZ1A00ebKPPqnFOiz5ci6U3b082xKb6xY_dXo8Y/edit#gid=1451198451

**Comment by sent-hil** [comment]
Just to close loops on this, we decided to go with lambda. https://codeforsanjose.slack.com/archives/C017G1BP02H/p1618615397103600
