### ISSUE TITLE
Research how to send emails

### ISSUE THREAD

**Issue by aaa12345678910** [codeforsanjose/gov-agenda-notifier#6]
Research how to send emails

**Comment by teohrt** [comment]
I know AWS has some nice functionality covering this: https://aws.amazon.com/ses/

This might be a nice way to go, especially if we go the AWS route.

**Comment by teohrt** [comment]
Twilio can do emails but it's more expensive than AWS. It starts at $15/month for up to 50,000 emails.
https://www.twilio.com/docs/sendgrid
https://sendgrid.com/pricing/

AWS' SES service is pay as you go at $0.10 per 1,000 emails sent.
https://aws.amazon.com/ses/
https://aws.amazon.com/ses/pricing/

AWS is clearly the most cost effective option here.
