### ISSUE TITLE
Style community member view subscribe page

### ISSUE THREAD

**Issue by jeffersonken19** [codeforsanjose/gov-agenda-notifier#72]
Find the full mocks here:
https://docs.google.com/document/d/1bsBU2OwlY0_BJ48z_6H8GPl-vv0a86lvGEPuGZqgvGo/edit#

<img width="390" alt="Screen Shot 2020-11-19 at 9 04 35 PM" src="https://user-images.githubusercontent.com/74744191/99761406-e0d82280-2aaa-11eb-8ba7-83ca7fd529af.png">

**Comment by anna-kartynnik** [comment]
1. Is it a styling only issue or should I integrate backend for subscribe action?

2. Are both phone number and email are required in this form or only one of them?

**Comment by anna-kartynnik** [comment]
Current progress:

![Screen Recording 2020-12-02 at 8 29 17 PM](https://user-images.githubusercontent.com/15210801/100964928-75e10f80-34de-11eb-8d8e-9ec8730fc3e5.gif)

TODO:

  - add backend integration if answer to question 1 above is "this is not styling only issue"
  - change checkbox styling (I was thinking about reusing CustomCheckbox from #75)

More questions:

3. Do we have any specific styles for invalid input fields? Like when user clicks Submit with empty required field, should we add red border to the input, for example?

4. I think we should indicate somehow when we wait some answer from the server. I've added a simple spinner, but do we have something similar in the mocks?
