### ISSUE TITLE
Backend - Auth Lambda - Implement Google SSO

### ISSUE THREAD

**Issue by teohrt** [codeforsanjose/gov-agenda-notifier#77]
Pending Austin working on it.

**Comment by jeffersonken19** [comment]
**Blocker: not sure which directory we should use.**

Passport JS should be hooked up like it should be.
Austin has already written up the resolvers & endpoints.
Not sure which strategy to use? AD or MS 365?

**Blocker: Not sure how to plug in the existing lambda architecture**

**Action items:**
Austin to follow up with Trace.
Annie to ask Matias if he knows which type of MS account they use.
