### ISSUE TITLE
Email Notification Implementation

### ISSUE THREAD

**Issue by teohrt** [codeforsanjose/gov-agenda-notifier#97]
The subscription controller is in the GraphQL API lambda. 

Modifications to the subscription controller is a good place to start: https://github.com/codeforsanjose/gov-agenda-notifier/blob/master/backend/graphql_api/lambda/controllers/subscriptionsController.js

Amazon SES is what we will be using to send emails:
https://aws.amazon.com/ses/

**Comment by jeffersonken19** [comment]
Senthil is still trying to get his environment up and running.
